### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by europer** [kanestoboi/AS5600#2]
Hi, great lib for the AS5600 and will try it since at given time trying to learn this new sensor and I do not find a lot info (strange) in internet about the AS5600.
Here my questions, in your layout you have 5V, GND, OUT, DIR, SCL, SDA and PGO.

1. 5V you can also use 3.3V since Im using a ESP32 (do I need to change something you your lib or in the .ino file?)
2. OUT = PWM?

3. SCL and SDA = I2C what Im using but with an Wemos Lonlin32 lite what dont have the standard pins so I do in 
 void setup()
{
  //Wire.begin(sdaPin, sclPin);
  Wire.begin(16, 17); //new SDA SCL pins
} and is ok so?
4. but can you explain me how to use DIR and PGO and are they implemented in your lib.
5. Can you give your experience of type of magnet and distance to AS5600, since I cant find any values just a distance from/to and that is must be  diametrical of course

since you have implemented lot of routines for the internal check of magnet flux if ok or to weak or strong do you have also a example where you are using all your routines in .ino file? 

Thanks in advance
Per

**Comment by kanestoboi** [comment]
Hi Per,

1. The AS5600 NEMA 17 Board can only use 5 V with the current revision (Rev 2). 3.3 V may be broken out in a future revision. You'll need to use a logic level converter if you want to use the ESP32.
2. That's correct, OUT = Analog/PWM output. More info on this can be found in the AS5600 datasheet.
3. I'm not familiar with the Wemos Lonlin32, however, that implementation seems right.
4. DIR pin is the direction pin. Set this pin HIGH to set clockwise as the position rotation direction. Set LOW for anti-clockwise to be the positive direction of rotation. More information can be found in the AS5600 datasheet.
5. Any diametrical will do. The automatic gain on the AS5600 will compensate for the magnet that you use.

The library does not automatically check the magnetic flux, this is automatically checked in the AS5600 hardware. You can call each function like any other function, for example, getStatus() can be used to derive if the internal gain has overflowed, meaning that the magnet is too close to the sensor.

Hope this helps.
