### ISSUE TITLE
Set analog range

### ISSUE THREAD

**Issue by vinshou** [kanestoboi/AS5600#3]
Hello,

Please can you help me ? I would like set range 0v 5v for out pin, can say me how program AS5600

**Comment by kanestoboi** [comment]
Hi vinshou,

you can use setOutputStage() to set the output.

setOutputStage(0) will set the output pin to analog (full range from 0% to 100% between GND and VDD). 

You can find more information on this in the AS5600 datasheet.

Hope this helps.
