### ISSUE TITLE
Using Multiple as5600 encoders

### ISSUE THREAD

**Issue by digitalbird01** [kanestoboi/AS5600#5]
Is there a way to use the library to read multiple encoders given that I am connecting them through a multiplexer?
If so how do I address the different encoders to the library?

**Comment by kanestoboi** [comment]
Hi @digitalbird01, 

After creating the AS5600 object with:
`AS5600 encoder;`

The encoder that is currently active through the multiplexer should be the one that is being read.

You should be able to use the same encoder object to command each AS5600.

**Comment by digitalbird01** [comment]
I will give that a go. Many thanks
